name: Deploy

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        id: deploy_step
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/aula-fipp-1-2026
            
            echo "Backup..."
            cp -r . ../backup-$(date +%F-%H-%M)

            echo "Atualizando..."
            git pull origin main

            echo "Reiniciando..."
            sudo systemctl restart flaskapp

      # ✅ SUCESSO
      - name: Notificar sucesso no Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "content": "✅ Deploy realizado com sucesso!"
              }' \
          ${{ secrets.DISCORD_WEBHOOK }}

      # ❌ ERRO
      - name: Notificar erro no Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "content": "❌ Erro no deploy! Verifique o GitHub Actions."
              }' \
          ${{ secrets.DISCORD_WEBHOOK }}
